baseurl = "/"
languageCode = "en-us"
title = "Kamil Slowikowski"
theme = "hugo-slowkow"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableGitInfo = true
enableEmoji = true

[permalinks]
  post = "/:year/:month/:day/:slug/"

[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    name = "Notes"
    title = "Notes"
    url = "/notes/"
    weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4

[params]
  googleAnalytics = "UA-15531613-2"
  absurl = "https://slowkow.com"
  twitter = "@slowkow"
  email = "kslowikowski@gmail.com"
  description = "Computational biology, bioinformatics, immunology, R, Python, Javascript, C++."
  cv = "Slowikowski-CV-2020-03-10.pdf"

  ## options for highlight.js (version, additional languages, and theme)
  #highlightjsVersion = "9.12.0"
  #highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  #highlightjsLang = ["r", "yaml"]
  ##highlightjsTheme = "github"

  MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
  MathJaxVersion = "2.7.5"

  # mainFont = "avenir"
  # mainFont = "georgia"
  mainFont = "helvetica"
  # mainFont = "baskerville"
  # bgColor = "near-white"
  bgColor = "light-gray"

  customCSS = ["css/custom.css"]

[params.urls]
  soumya = "https://immunogenomics.hms.harvard.edu/"
  brenner = "https://www.hms.harvard.edu/dms/immunology/fac/Brenner.php"

[params.logo]
  url = "profile_2018.jpg"
  width = 50
  height = 50
  alt = "Kamil Slowikowski"

[taxonomies]
  tag = "tags"
  category = "categories"

